baseURL = 'https://example.org/'
languageCode = 'it-it'
title = 'Personal WebSite'
theme = 'blowfish'

[params]
	mainSections = ["posts"]

	[params.homepage]
		layout = "profile"
		showRecent = true
		showRecentItems = 5
		showMoreLink = true
		showMoreLinkDest = "/posts/"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
