baseURL = 'https://example.org/'
languageCode = 'it-it'
title = 'Federico Mantua'
theme = 'blowfish'

[params]
	mainSections = ["posts"]
	disableTextInHeader = true

	[params.Author]
		name = "Federico Mantua"
		headline = "Team Leader / Software Engineer"
		bio = "Microsoft Solution C# .NET"
		linkedin = ""

	[params.homepage]
		layout = "profile"
		showRecent = true
		showRecentItems = 5
		showMoreLink = true
		showMoreLinkDest = "/posts/"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
